export enum MoneyOrderStatus {
  INITIATED = 'PENDING',

  PROCESSING = 'PROCESSING',

  ON_HOLD = 'ON_HOLD',
  COMPLETED = 'COMPLETED',
  
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}

export enum MoneyOrderDeliveryStatus {
    DELIVERY_NOT_AUTHORIZED = 'DELIVERY_NOT_AUTHORIZED',

    DELIVERY_AUTHORIZED = 'DELIVERY_AUTHORIZED',
    DELIVERY_INITIATED = 'DELIVERY_INITIATED',

    DELIVERY_COMPLETED = 'DELIVERY_COMPLETED',
    DELIVERY_FAILED = 'DELIVERY_FAILED',
}