export const WALLET_SERVICE = Symbol('WALLET_SERVICE');
export const WALLET_TRANSACTION_SERVICE = Symbol('WALLET_TRANSACTION_SERVICE');
export const WALLET_REPO = Symbol('WALLET_REPO');
export const WALLET_TRANSACTION_REPO = Symbol('WALLET_TRANSACTION_REPO');
